import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1785597769394 implements MigrationInterface {
    name = 'InitSchema1785597769394'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "actividades_evidencias" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "descripcion" text, "imagenes" text array NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_80fe46234ea40ea9902e460ff60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividad_insumos" ("id" SERIAL NOT NULL, "actividad_id" integer NOT NULL, "insumo_id" integer NOT NULL, "cantidad_usada" double precision NOT NULL, "unidad" character varying NOT NULL, "costo_unitario" double precision NOT NULL, "costo_total" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_fb5408a812468877d2ddff781fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_herramientas" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "insumoId" integer NOT NULL, "activoFijoId" integer, "horasEstimadas" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_c200df45d285b54e6f9b4f97d07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividad_historial" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "cultivoId" integer NOT NULL, "usuarioId" integer NOT NULL, "motivo" text NOT NULL, "cambios" json NOT NULL, "fecha" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fef3b6c8bcc62e5c865259134c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_insumos_reserva" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "insumoId" integer NOT NULL, "cantidadReservada" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3dafed0fb9b36627965a5dd8886" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_insumos_uso" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "insumoId" integer NOT NULL, "cantidadUso" double precision NOT NULL, "costoUnitarioUso" double precision NOT NULL, "costoTotal" double precision NOT NULL, "movimientoInsumoId" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0cc0ff2c078a7616db43b05bd30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_responsables" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "usuarioId" integer NOT NULL, "horas" double precision NOT NULL, "precioHora" double precision NOT NULL, "costo" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_cea86013f6ee0e97666cc2bbef2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades_servicios" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "nombreServicio" character varying NOT NULL, "proveedorId" integer NOT NULL, "maquinariaId" integer NOT NULL, "horas" double precision NOT NULL, "precioHora" double precision NOT NULL, "costo" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_2ec0c214a83cbe1ed246f5cb372" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "actividades" ("id" SERIAL NOT NULL, "nombre" character varying(150) NOT NULL, "tipo" character varying(50) NOT NULL, "subtipo" character varying(50), "lote_id" integer NOT NULL, "sub_lote_id" integer, "cultivo_id" integer NOT NULL, "fecha" date NOT NULL, "horas_actividad" double precision NOT NULL, "precio_hora_actividad" double precision NOT NULL, "descripcion" text, "creado_por_usuario_id" integer NOT NULL, "cantidad_plantas" integer, "producto_agro_id" integer, "estado" character varying NOT NULL DEFAULT 'Pendiente', "costoManoObra" numeric, "kgRecolectados" numeric, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_03490866fef1c23456f0e289d9c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cultivos" ("id" SERIAL NOT NULL, "nombreCultivo" character varying NOT NULL, "tipoCultivo" character varying NOT NULL, "lote_id" integer NOT NULL, "sub_Lote_id" integer, "fechaSiembra" TIMESTAMP NOT NULL, "fechaFinalizacion" TIMESTAMP, "costoTotal" double precision NOT NULL DEFAULT '0', "estado" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f7b1d6fc0a6976acd023dca2d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cultivo_historial" ("id" SERIAL NOT NULL, "cultivo_id" integer NOT NULL, "usuario_id" integer NOT NULL, "motivo" text NOT NULL, "cambios" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1444e12287840811dfcac8dd99d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "lotes_produccion" ("id" SERIAL NOT NULL, "producto_agro_id" integer NOT NULL, "cultivo_id" integer NOT NULL, "lote_id" integer NOT NULL, "sub_lote_id" integer, "actividades_cosecha_id" integer, "calidad" character varying NOT NULL, "cantidad_kg" double precision NOT NULL, "stock_disponible_kg" double precision NOT NULL, "costo_unitario_kg" double precision NOT NULL, "costo_total" double precision NOT NULL, "precio_sugerido_kg" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_245f08534328efe79cc2cc1ccd8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "movimientos_produccion" ("id" SERIAL NOT NULL, "loteProduccionId" integer NOT NULL, "tipo" character varying NOT NULL, "cantidadKg" double precision NOT NULL, "costoUnitarioKg" double precision NOT NULL, "precioUnitarioKg" double precision NOT NULL, "costoTotal" double precision NOT NULL, "ventaId" integer, "descripcion" text, "usuarioId" integer NOT NULL, "fecha" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_b60c7034e7a75bb9249293644da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usos_herramientas" ("id" SERIAL NOT NULL, "actividadId" integer NOT NULL, "insumoId" integer NOT NULL, "horasUsadas" double precision NOT NULL, "depreciacionGenerada" double precision NOT NULL, "valorLibrosAntes" double precision NOT NULL, "valorLibrosDespues" double precision NOT NULL, "fechaUso" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_baf7a579a302b90a613f660f438" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "usos_herramientas"`);
        await queryRunner.query(`DROP TABLE "movimientos_produccion"`);
        await queryRunner.query(`DROP TABLE "lotes_produccion"`);
        await queryRunner.query(`DROP TABLE "cultivo_historial"`);
        await queryRunner.query(`DROP TABLE "cultivos"`);
        await queryRunner.query(`DROP TABLE "actividades"`);
        await queryRunner.query(`DROP TABLE "actividades_servicios"`);
        await queryRunner.query(`DROP TABLE "actividades_responsables"`);
        await queryRunner.query(`DROP TABLE "actividades_insumos_uso"`);
        await queryRunner.query(`DROP TABLE "actividades_insumos_reserva"`);
        await queryRunner.query(`DROP TABLE "actividad_historial"`);
        await queryRunner.query(`DROP TABLE "actividades_herramientas"`);
        await queryRunner.query(`DROP TABLE "actividad_insumos"`);
        await queryRunner.query(`DROP TABLE "actividades_evidencias"`);
    }

}
